Author - Benjamin Brock
Project title - Predicting Heart attacks via feed forward neural network.
Date - 10/01/23

Description:

Using the dataset available @ https://www.kaggle.com/datasets/rashikrahmanpritom/heart-attack-analysis-prediction-dataset
this short project aimed to predict whether the individual has had or is likely to have a heart attack. 

It is important to note that this data set is very limited with only a handful of data entries. As such, this exercise is purely a proof of concept and would require much larger datasets and testing to prove reliable. 

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras import Sequential
from keras.layers import Dense, Dropout, Input
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [4]:
import os
os.environ['KAGGLE_USERNAME'] = 'benjaminbrock'
os.environ['KAGGLE_KEY'] = '6f7f43875d0baa37946d4508865163df'
!kaggle datasets download -d rashikrahmanpritom/heart-attack-analysis-prediction-dataset

  0% 0.00/4.11k [00:00<?, ?B/s]
100% 4.11k/4.11k [00:00<00:00, 10.3MB/s]


In [5]:
!unzip /content/heart-attack-analysis-prediction-dataset.zip

Archive:  /content/heart-attack-analysis-prediction-dataset.zip
  inflating: heart.csv               
  inflating: o2Saturation.csv        


In [6]:
df = pd.read_csv('heart.csv')

In [7]:
print(df.head)

<bound method NDFrame.head of      age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  outp

In [8]:
Outputs = df.pop('output')
print (Outputs)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64


In [9]:
print(df.head)

<bound method NDFrame.head of      age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0  

In [10]:
def normalise(Data):
    Norm = MinMaxScaler(feature_range= (0,1))
    N_Data = Norm.fit_transform(np.array(Data))
    return N_Data

In [11]:
NormData = normalise(df)

In [12]:
print (NormData)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [13]:
print (len(NormData))
val_split = 0.9
Train, Val = NormData[0:int(val_split*len(NormData))] , NormData[int(val_split*len(NormData)): len(NormData)]

303


In [14]:
Label, Val_label = Outputs[0:int(val_split*len(Outputs))] , Outputs[int(val_split*len(Outputs)): len(Outputs)]

In [15]:
model = Sequential()
model.add(Input(shape = 13))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))
#model.compile(loss = 'mse', optimizer = 'Adam')
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [16]:
model.fit(Train,Label, epochs = 100 )

Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/backend.py:5703: UserWarning: "`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Sigmoid activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


9/9 [==============================] - 2s 2ms/step - loss: 0.6441 - accuracy: 0.7390
Epoch 2/100
9/9 [==============================] - 0s 1ms/step - loss: 0.6086 - accuracy: 0.7610
Epoch 3/100
9/9 [==============================] - 0s 1ms/step - loss: 0.5795 - accuracy: 0.7537
Epoch 4/100
9/9 [==============================] - 0s 1ms/step - loss: 0.5512 - accuracy: 0.7721
Epoch 5/100
9/9 [==============================] - 0s 1ms/step - loss: 0.5228 - accuracy: 0.7904
Epoch 6/100
9/9 [==============================] - 0s 1ms/step - loss: 0.4974 - accuracy: 0.8162
Epoch 7/100
9/9 [==============================] - 0s 2ms/step - loss: 0.4720 - accuracy: 0.8162
Epoch 8/100
9/9 [==============================] - 0s 1ms/step - loss: 0.4487 - accuracy: 0.8199
Epoch 9/100
9/9 [==============================] - 0s 1ms/step - loss: 0.4271 - accuracy: 0.8088
Epoch 10/100
9/9 [==============================] - 0s 2ms/step - loss: 0.4128 - accuracy: 0.8162
Epoch 11/100
9/9 [=======================

In [17]:
#print(len(Train))
#A value equal to or above 
print(Label[270])
print(model.predict(Train)[270])

0
9/9 [==============================] - 0s 1ms/step
[0.264345]


There is limit data to go off in this data set and as such a NN appraoch may not be the ideal solution. Fortunately, the SKLearn package contains several preset algorithms to compare it against.

In [19]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

from sklearn.svm import SVC 

svc = SVC(kernel='linear')

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

from sklearn import neighbors

knn = neighbors.KNeighborsClassifier(n_neighbors=5)


In [20]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())
model.fit(Train, Label)
model.score(Train, Label)

0.5542336719246868

In [21]:
svc.fit(Train , Label)
svc.score(Train, Label)


0.8639705882352942

In [22]:
knn.fit(Train , Label)
knn.score(Train, Label)


0.8786764705882353