Author - Benjamin Brock
Project title - Predicting Heart attacks via feed forward neural network.
Date - 10/01/23

Description:

Using the dataset available @ https://www.kaggle.com/datasets/rashikrahmanpritom/heart-attack-analysis-prediction-dataset
this short project aimed to predict whether the individual has had or is likely to have a heart attack. 

It is important to note that this data set is very limited with only a handful of data entries. As such, this exercise is purely a proof of concept and would require much larger datasets and testing to prove reliable. 

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras import Sequential
from keras.layers import Dense, Dropout, Input
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
print(df.head)

<bound method NDFrame.head of      age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  outp

In [4]:
Outputs = df.pop('output')
print (Outputs)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64


In [5]:
print(df.head)

<bound method NDFrame.head of      age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0  

In [6]:
def normalise(Data):
    Norm = MinMaxScaler(feature_range= (0,1))
    N_Data = Norm.fit_transform(np.array(Data))
    return N_Data

In [7]:
NormData = normalise(df)

In [8]:
print (NormData)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [9]:
print (len(NormData))
val_split = 0.9
Train, Val = NormData[0:int(val_split*len(NormData))] , NormData[int(val_split*len(NormData)): len(NormData)]

303


In [10]:
Label, Val_label = Outputs[0:int(val_split*len(Outputs))] , Outputs[int(val_split*len(Outputs)): len(Outputs)]

In [21]:
model = Sequential()
model.add(Input(shape = 13))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(32))
model.add(Dense(1, activation = 'sigmoid'))
#model.compile(loss = 'mse', optimizer = 'Adam')
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [22]:
model.fit(Train,Label, epochs = 100 )

Epoch 1/100
9/9 [==============================] - 1s 4ms/step - loss: 0.7060 - accuracy: 0.5919
Epoch 2/100
9/9 [==============================] - 0s 4ms/step - loss: 0.6689 - accuracy: 0.6029
Epoch 3/100
9/9 [==============================] - 0s 4ms/step - loss: 0.6351 - accuracy: 0.6287
Epoch 4/100
9/9 [==============================] - 0s 3ms/step - loss: 0.6022 - accuracy: 0.6912
Epoch 5/100
9/9 [==============================] - 0s 3ms/step - loss: 0.5669 - accuracy: 0.7463
Epoch 6/100
9/9 [==============================] - 0s 3ms/step - loss: 0.5302 - accuracy: 0.7831
Epoch 7/100
9/9 [==============================] - 0s 3ms/step - loss: 0.4939 - accuracy: 0.8015
Epoch 8/100
9/9 [==============================] - 0s 4ms/step - loss: 0.4600 - accuracy: 0.8272
Epoch 9/100
9/9 [==============================] - 0s 3ms/step - loss: 0.4310 - accuracy: 0.8309
Epoch 10/100
9/9 [==============================] - 0s 4ms/step - loss: 0.4088 - accuracy: 0.8346
Epoch 11/100
9/9 [===========

In [23]:
print(model.predict(Val))
print(np.argmax(model.predict(Val)[0]))

1/1 [==============================] - 0s 64ms/step
[[0.19715525]
 [0.6928229 ]
 [0.06397677]
 [0.29180294]
 [0.03725443]
 [0.84625936]
 [0.94230384]
 [0.01090397]
 [0.16858947]
 [0.4692683 ]
 [0.8675451 ]
 [0.8849998 ]
 [0.04597155]
 [0.00234902]
 [0.85695124]
 [0.765554  ]
 [0.01033528]
 [0.02257808]
 [0.7842709 ]
 [0.00131142]
 [0.00197941]
 [0.48047975]
 [0.04403328]
 [0.00369592]
 [0.76651174]
 [0.07253613]
 [0.19752614]
 [0.6572777 ]
 [0.00785997]
 [0.06133366]
 [0.9679275 ]]
1/1 [==============================] - 0s 22ms/step
0


In [24]:
Hold = []
for i in range(len(Val)):
  Hold.append((np.argmax(model.predict(Val)[i])))

1/1 [==============================] - 0s 21ms/step


In [25]:
print(Hold)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [26]:
print(Val_label)

272    0
273    0
274    0
275    0
276    0
277    0
278    0
279    0
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    0
288    0
289    0
290    0
291    0
292    0
293    0
294    0
295    0
296    0
297    0
298    0
299    0
300    0
301    0
302    0
Name: output, dtype: int64
